/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./src/components/authLayout/index.vue')['default']
    Content: typeof import('./src/components/authLayout/content.vue')['default']
    DefaultLayout: typeof import('./src/components/defaultLayout/index.vue')['default']
    DropDown: typeof import('./src/components/emailLayout/drop-down.vue')['default']
    EmailLayout: typeof import('./src/components/emailLayout/index.vue')['default']
    Footer: typeof import('./src/components/authLayout/footer.vue')['default']
    Header: typeof import('./src/components/authLayout/header.vue')['default']
    LayoutHeader: typeof import('./src/components/emailLayout/layout-header.vue')['default']
    LayoutSidebar: typeof import('./src/components/emailLayout/layout-sidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
